# Generated by Django 5.2.7 on 2025-11-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandWrittenApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='email',
        ),
        migrations.AddField(
            model_name='userlogin',
            name='Username',
            field=models.CharField(default=2, unique=True),
            preserve_default=False,
        ),
    ]
