# Generated by Django 5.2.7 on 2025-11-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HandWrittenApp', '0002_remove_userlogin_email_userlogin_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersignup',
            old_name='confirm_password',
            new_name='userName',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='last_name',
        ),
    ]
