# Generated by Django 5.2.7 on 2025-11-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandWrittenApp', '0003_rename_confirm_password_usersignup_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Images/')),
            ],
        ),
        migrations.DeleteModel(
            name='UserLogin',
        ),
        migrations.DeleteModel(
            name='UserSignup',
        ),
    ]
