# Generated by Django 5.2.7 on 2025-11-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandWrittenApp', '0004_predictionimage_delete_userlogin_delete_usersignup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionimage',
            name='Image',
            field=models.ImageField(upload_to='media/media/'),
        ),
    ]
