# Generated by Django 5.2.7 on 2025-11-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandWrittenApp', '0005_alter_predictionimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionimage',
            name='Image',
            field=models.ImageField(default='qw.png', upload_to=''),
        ),
    ]
