# Generated by Django 6.0 on 2025-12-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandWrittenApp', '0008_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictionimage',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='predictionimage',
            name='prediction_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionimage',
            name='image',
            field=models.ImageField(upload_to='predictions/'),
        ),
    ]
